In [1]:
import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt 
import numpy as np

In [2]:
#___________ feature construction

In [6]:
df = sns.load_dataset('titanic')
df = df[['age','pclass','sibsp','parch','survived']]

In [8]:
df.head(3)

    age  pclass  sibsp  parch  survived
0  22.0       3      1      0         0
1  38.0       1      1      0         1
2  26.0       3      0      0         1

In [9]:
df.dropna(inplace=True)

In [10]:
df.head(2)

    age  pclass  sibsp  parch  survived
0  22.0       3      1      0         0
1  38.0       1      1      0         1

In [11]:
X=df.iloc[:,0:4]
y=df.iloc[:,-1]

In [12]:
X.head()

    age  pclass  sibsp  parch
0  22.0       3      1      0
1  38.0       1      1      0
2  26.0       3      0      0
3  35.0       1      1      0
4  35.0       3      0      0

In [17]:
X['family_size']= X['sibsp']+X['parch']+1

In [18]:
X.head()

    age  pclass  sibsp  parch  family_size
0  22.0       3      1      0            2
1  38.0       1      1      0            2
2  26.0       3      0      0            1
3  35.0       1      1      0            2
4  35.0       3      0      0            1

In [20]:
def myfunc(num):
    if num==1:
        return 0
    elif num>1 and num<=4:
        return 1
    else:
        return 2
myfunc(4)

1

In [24]:
X['Family_Type']= X['family_size'].apply(myfunc)

In [25]:
X.head()

    age  pclass  sibsp  parch  family_size  Family_Type
0  22.0       3      1      0            1            0
1  38.0       1      1      0            1            0
2  26.0       3      0      0            0            2
3  35.0       1      1      0            1            0
4  35.0       3      0      0            0            2

In [27]:
X.drop(columns = ['sibsp','parch','family_size'],inplace=True)

In [28]:
X.head()

    age  pclass  Family_Type
0  22.0       3            0
1  38.0       1            0
2  26.0       3            2
3  35.0       1            0
4  35.0       3            2

In [29]:
#____feature splitting

In [41]:
t = pd.read_csv('cars.csv')

In [48]:
t.describe()

,Cylinders,Valves_Per_Cylinder,Doors,Seating_Capacity,Number_of_Airbags,USB_Ports
count,1210.000000,1174.000000,1272.000000,1270.000000,1141.000000,29.000000
mean,4.380992,3.977853,4.550314,5.270079,3.787029,1.793103
std,1.660957,0.833763,0.747816,1.145231,2.522399,0.773642
min,2.000000,1.000000,2.000000,2.000000,1.000000,1.000000
25%,4.000000,4.000000,4.000000,5.000000,2.000000,1.000000
50%,4.000000,4.000000,5.000000,5.000000,2.000000,2.000000
75%,4.000000,4.000000,5.000000,5.000000,6.000000,2.000000
max,16.000000,16.000000,5.000000,16.000000,14.000000,3.000000

In [54]:
df = sns.load_dataset('tips')

In [55]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [58]:
X=df.iloc[:,0:]
y=df.iloc[:,-1]

In [59]:
X.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [64]:
X['bill_per_person']= df['total_bill']/df['size']

In [65]:
X.head()

,total_bill,tip,sex,smoker,day,time,size,total_tip_per_person,bill_per_person
0,16.99,1.01,Female,No,Sun,Dinner,2,0.505000,8.495000
1,10.34,1.66,Male,No,Sun,Dinner,3,0.553333,3.446667
2,21.01,3.50,Male,No,Sun,Dinner,3,1.166667,7.003333
3,23.68,3.31,Male,No,Sun,Dinner,2,1.655000,11.840000
4,24.59,3.61,Female,No,Sun,Dinner,4,0.902500,6.147500

In [66]:
#curse of dimensionality